name: Labeler
on:
  pull_request:
    branches: [ "master","main" ]
    types: [ opened, synchronize, reopened ]
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler_config.yml
          sync-labels: true